config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  namespace :admin do
    resources :meats
    resources :side_dishes
    resources :orders
  end

  resources :orders
end

app/models/meat.rb
class Meat < ActiveRecord::Base
  before_destroy :check_for_orders

  has_many :order_meats
  has_many :orders, through: :order_meats

  validates :name, presence: true, uniqueness: true

  private

  def check_for_orders
    if orders.any?
      errors[:base] << "cannot delete meat that has already been ordered"
      return false
    end
  end
end

app/controllers/admin/meats_controller.rb
class Admin::MeatsController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :read, Meat
    @meats = Meat.all
  end

  def show
    authorize! :read, Meat
    @meat = Meat.find(params[:id])
  end

  def new
    authorize! :create, Meat
    @meat = Meat.new
  end

  def create
    authorize! :create, Meat
    @meat = Meat.new(meat_params)

    if @meat.save
      respond_with @meat, location: [:admin, @meat]
    else
      render 'new'
    end
  end

  def edit
    authorize! :update, Meat
    @meat = Meat.find(params[:id])
  end

  def update
    authorize! :update, Meat
    @meat = Meat.find(params[:id])
    @meat.update_attributes(meat_params)
    respond_with @meat, location: [:admin, @meat]
  end

  def destroy
    authorize! :destroy, Meat
    @meat = Meat.find(params[:id])
    @meat.destroy
    respond_with @meat, location: admin_meats_path
  end

  private

  def meat_params
    params.require(:meat).permit(:name)
  end
end

app/controllers/meats_controller.rb
class MeatsController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html

  def index
    @meats = Meat.all
  end

  def show
    @meat = Meat.find(params[:id])
  end

  def new
    @meat = Meat.new
  end

  def create
    @meat = Meat.new(meat_params)

    if @meat.save
      respond_with @meat
    else
      render 'new'
    end
  end

  def edit
    @meat = Meat.find(params[:id])
  end

  def update
    @meat = Meat.find(params[:id])
    @meat.update_attributes(meat_params)
    respond_with @meat
  end

  def destroy
    @meat = Meat.find(params[:id])
    @meat.destroy

    redirect_to meats_path
  end

  private

  def meat_params
    params.require(:meat).permit(:name)
  end
end

app/views/admin/meats/_form.html.erb
<div class="row">
  <%= simple_form_for [:admin, @meat], html: { class: 'form-horizontal' } do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
        <div class="form-group">
          <div class="col-sm-6">
            <%= f.input :name %>
          </div>
        </div>
    </div>

    <div class="form-actions">
      <div class="form-group text-center">
        <%= f.button :submit, button_label, class: 'btn btn-flat inverse' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/meats/edit.html.erb
<h2>Editar Carne</h2>
<br />
<%= render 'form', button_label: 'Editar carne' %>

app/views/admin/meats/index.html.erb
<table class="table table-striped">

  <thead>
    <th>#</th>
    <th>Carne</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% @meats.each do |meat| %>
      <tr>
        <td><%= meat.id %></td>
        <td><%= meat.name %></td>
        <td><%= link_to 'Exibir', admin_meat_path(meat) %></td>
        <td><%= link_to 'Editar', edit_admin_meat_path(meat) %></td>
        <td><%= link_to 'Deletar', admin_meat_path(meat), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/meats/new.html.erb
<h2 class="text-center">Cadastrar Carne</h2>
<br />
<%= render 'form', button_label: 'Cadastrar Carne' %>

app/views/admin/meats/show.html.erb
<table class="table table-striped">
  <thead>
    <th>#</th>
    <th>Nome</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @meat.id %></td>
      <td><%= @meat.name %></td>
    </tr>
  </tbody>
</table>