config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  namespace :admin do
    resources :meats
    resources :side_dishes
    resources :orders
  end

  resources :orders
end

app/models/side_dish.rb
class SideDish < ActiveRecord::Base
  before_destroy :check_for_orders

  has_many :order_side_dishes
  has_many :orders, through: :order_side_dishes

  validates :name, presence: true, uniqueness: true

  private

  def check_for_orders
    if orders.any?
      errors[:base] << "cannot delete side dish that has already been ordered"
      return false
    end
  end
end

app/controllers/admin/side_dishes_controller.rb
class Admin::SideDishesController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :read, SideDish
    @side_dishes = SideDish.all
  end

  def show
    authorize! :read, SideDish
    @side_dish = SideDish.find(params[:id])
  end

  def new
    authorize! :create, SideDish
    @side_dish = SideDish.new
  end

  def create
    authorize! :create, SideDish
    @side_dish = SideDish.new(side_dish_params)

    if @side_dish.save
      respond_with @side_dish, location: [:admin, @side_dish]
    else
      render 'new'
    end
  end

  def edit
    authorize! :update, SideDish
    @side_dish = SideDish.find(params[:id])
  end

  def update
    authorize! :update, SideDish
    @side_dish = SideDish.find(params[:id])
    @side_dish.update_attributes(side_dish_params)
    respond_with @side_dish, location: [:admin, @side_dish]
  end

  def destroy
    authorize! :destroy, SideDish
    @side_dish = SideDish.find(params[:id])
    @side_dish.destroy
    respond_with @side_dish, location: admin_side_dishes_path
  end

  private

  def side_dish_params
    params.require(:side_dish).permit(:name)
  end
end

app/controllers/side_dishes_controller.rb
class SideDishesController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html

  def index
    @side_dishes = SideDish.all
  end

  def show
    @side_dish = SideDish.find(params[:id])
  end

  def new
    @side_dish = SideDish.new
  end

  def create
    @side_dish = SideDish.new(side_dish_params)

    if @side_dish.save
      respond_with @side_dish
    else
      render 'new'
    end
  end

  def edit
    @side_dish = SideDish.find(params[:id])
  end

  def update
    @side_dish = SideDish.find(params[:id])
    @side_dish.update_attributes(side_dish_params)
    respond_with @side_dish
  end

  def destroy
    @side_dish = SideDish.find(params[:id])
    @side_dish.destroy

    redirect_to side_dishes_path
  end

  private

  def side_dish_params
    params.require(:side_dish).permit(:name)
  end
end

app/views/admin/side_dishes/_form.html.erb
<div class="row">
  <%= simple_form_for [:admin, @side_dish], html: { class: 'form-horizontal' } do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
        <div class="form-group">
          <div class="col-sm-6">
            <%= f.input :name %>
          </div>
        </div>
    </div>

    <div class="form-actions">
      <div class="form-group text-center">
        <%= f.button :submit, button_label, class: 'btn btn-flat inverse' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/side_dishes/edit.html.erb
<h2>Editar Acompanhamento</h2>
<br />
<%= render 'form', button_label: 'Editar acompanhamento' %>

app/views/admin/side_dishes/index.html.erb
<table class="table table-striped">

  <thead>
    <th>#</th>
    <th>Acompanhamento</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% @side_dishes.each do |side_dish| %>
      <tr>
        <td><%= side_dish.id %></td>
        <td><%= side_dish.name %></td>
        <td><%= link_to 'Exibir', admin_side_dish_path(side_dish) %></td>
        <td><%= link_to 'Editar', edit_admin_side_dish_path(side_dish) %></td>
        <td><%= link_to 'Deletar', admin_side_dish_path(side_dish), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/side_dishes/new.html.erb
<h2 class="text-center">Cadastrar Acompanhamento</h2>
<br />
<%= render 'form', button_label: 'Cadastrar Acompanhamento' %>

app/views/admin/side_dishes/show.html.erb
<table class="table table-striped">
  <thead>
    <th>#</th>
    <th>Nome</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @side_dish.id %></td>
      <td><%= @side_dish.name %></td>
    </tr>
  </tbody>
</table>