config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }

  namespace :admin do
    resources :meats
    resources :side_dishes
    resources :orders
  end

  resources :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_meats, dependent: :destroy
  has_many :meats, through: :order_meats
  has_many :order_side_dishes, dependent: :destroy
  has_many :side_dishes, through: :order_side_dishes
  has_one :address, dependent: :destroy

  accepts_nested_attributes_for :meats
  accepts_nested_attributes_for :side_dishes
  accepts_nested_attributes_for :address

  validates_presence_of :address, :meats, :side_dishes
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :read, Order
    @orders = Order.all
  end

  def show
    authorize! :read, Order
    @order = Order.find(params[:id])
  end

  def new
    authorize! :create, Order
    @order = Order.new
    @order.meats.build
    @order.side_dishes.build
    @order.build_address
  end

  def create
    authorize! :create, Order
    @order = Order.new(order_params)
    @order.user = current_user

    if @order.save
      respond_with @order, location: [:admin, @order]
    else
      render 'new'
    end
  end

  def edit
    authorize! :update, Order
    @order = Order.find(params[:id])
  end

  def update
    authorize! :update, Order
    @order = Order.find(params[:id])
    @order.update_attributes(order_params)
    respond_with @order, location: [:admin, @order]
  end

  def destroy
    authorize! :destroy, Order
    @order = Order.find(params[:id])
    @order.destroy

    respond_with @order, location: admin_orders_path
  end

  private

  def order_params
    params.require(:order).permit(
      meat_ids: [],
      side_dish_ids: [],
      address_attributes: [:street, :number, :reference]
    )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :read, Order
    redirect_to root_url
  end

  def show
    @order = Order.find(params[:id])
    authorize! :read, @order
  end

  def new
    authorize! :create, Order
    @order = Order.new
    @order.meats.build
    @order.side_dishes.build
    @order.build_address
  end

  def create
    authorize! :create, Order
    @order = Order.new(order_params)
    @order.user = current_user

    if @order.save
      respond_with @order
    else
      render 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
    authorize! :update, @order
  end

  def update
    authorize! :update, Order
    @order = Order.find(params[:id])
    @order.update_attributes(order_params)
    respond_with @order
  end

  def destroy
    authorize! :destroy, Order
    @order = Order.find(params[:id])
    @order.destroy

    respond_with @order, location: orders_path
  end

  private

  def order_params
    params.require(:order).permit(
      meat_ids: [],
      side_dish_ids: [],
      address_attributes: [:street, :number, :reference]
    )
  end
end

app/views/orders/index.html.erb
<table class="table table-striped">

  <thead>
    <th>#</th>
    <th>Carnes</th>
    <th>Acompanhamentos</th>
    <th>Endereço</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td>
          <% order.meats.each do |meat| %>
            <ul class="list-unstyled">
              <li><%= meat.name %></li>
            </ul>
          <% end %>
        </td>
        <td>
          <% order.side_dishes.each do |side_dish| %>
            <ul class="list-unstyled">
              <li><%= side_dish.name %></li>
            </ul>
          <% end %>
        </td>
        <td>
          <% if order.address %>
            <ul class="list-unstyled">
              <li>Rua: <%= order.address.street %></li>
              <li>Número: <%= order.address.number %></li>
              <li>Referência: <%= order.address.reference %></li>
            </ul>
          <% end %>
        </td>
        <td><%= link_to 'Exibir', order_path(order) %></td>
        <td><%= link_to 'Editar', edit_order_path(order) %></td>
        <td><%= link_to 'Deletar', order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/show.html.erb
<table class="table table-striped">
  <thead>
    <th>#</th>
    <th>Carnes</th>
    <th>Acompanhamentos</th>
    <th>Endereço</th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
    <tr>
      <td><%= @order.id %></td>
      <td>
        <% @order.meats.each do |meat| %>
          <ul class="list-unstyled">
            <li><%= meat.name %></li>
          </ul>
        <% end %>
      </td>
      <td>
        <% @order.side_dishes.each do |side_dish| %>
          <ul class="list-unstyled">
            <li><%= side_dish.name %></li>
          </ul>
        <% end %>
      </td>
      <td>
        <ul class="list-unstyled">
          <li>Rua: <%= @order.address.street %></li>
          <li>Número: <%= @order.address.number %></li>
          <li>Referência: <%= @order.address.reference %></li>
        </ul>
      </td>
      <td><%= link_to 'Alterar pedido', edit_order_path(@order) if can? :update, @order %></td>
      <td><%= link_to 'Cancelar', order_path(@order), method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, @order %></td>
    </tr>
  </tbody>
</table>